from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from app.analytics.context import AnalysisContext
from app.schemas.analysis import (
    AnalyticsEngineMetaResponse,
    AnalyticsSignalResponse,
    EngineKPI,
    EngineRunResponse,
)


class AnalyticalEngine(ABC):
    """Authoritative base interface for all ten SAT-SA analytical engines.
    Ensures decoupled, independently executable supervisory analytics.
    """
    id: str = "GENERIC_ENGINE"
    slug: str = "generic"
    name: str = "Generic Engine"
    short_name: str = "Generic"
    purpose: str = "Base analytical engine"
    icon_name: str = "hub"
    route: str = "/analysis/generic"
    version: str = "1.0.0"
    rule_version: str = "RULE-1.0.0"
    pipeline_version: str = "SAT-SA-2026.3"

    @abstractmethod
    def compute(self, context: AnalysisContext) -> List[AnalyticsSignalResponse]:
        """Execute core analytical algorithms over evidence, telemetry, and control datasets."""
        raise NotImplementedError

    @abstractmethod
    def get_kpis(self, signals: List[AnalyticsSignalResponse], context: AnalysisContext) -> List[EngineKPI]:
        """Compute exactly 4 primary supervisory KPIs required by the analytical UI."""
        raise NotImplementedError

    def explain(self, signal: AnalyticsSignalResponse) -> str:
        """Provide detailed statutory explanation and evidence linkage for an identified signal."""
        return (
            f"Supervisory Signal {signal.signal_id} generated by {self.name} (v{self.version}). "
            f"Expected: {signal.expected}. Observed: {signal.observed}. "
            f"Discrepancy: {signal.difference}. Linked Evidence: {', '.join(signal.evidence_ids) if signal.evidence_ids else 'None'}."
        )

    def get_trend_comparison(self, signals: List[AnalyticsSignalResponse], context: AnalysisContext) -> Optional[Dict[str, Any]]:
        """Optional trend or peer comparison dataset for engine visualization."""
        return None

    def get_meta(self, signal_count: int = 0) -> AnalyticsEngineMetaResponse:
        return AnalyticsEngineMetaResponse(
            id=self.id,
            slug=self.slug,
            name=self.name,
            short_name=self.short_name,
            shortName=self.short_name,
            purpose=self.purpose,
            icon_name=self.icon_name,
            iconName=self.icon_name,
            signal_count=signal_count,
            signalCount=signal_count,
            status="Active",
            route=self.route,
            version=self.version,
        )
