from datetime import datetime
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.api.deps import get_db, require_auth, check_cse_access
from app.db.models.user import User
from app.schemas.finding import (
    SignalResponse,
    FindingResponse,
    ExaminerWorkspaceResponse,
    ReviewQueueResponse,
    FindingDecisionRequest,
    EvidenceDemandRequest,
)
from app.services.finding_service import FindingService

router = APIRouter(tags=["Findings & Review Queue"])


# 1. Signal Detail Retrieval (TASK GROUP 1)
@router.get("/signals/{signal_id}", response_model=SignalResponse, summary="Retrieve Analytical Signal Detail")
def get_signal_detail(
    signal_id: str,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Retrieve full analytical signal details generated by analytical engines."""
    return FindingService.get_signal(db=db, signal_id=signal_id)


# 2. Finding List & Search (TASK GROUP 4)
@router.get("/findings", response_model=List[FindingResponse], summary="Query and Filter Findings")
@router.get("/review/findings", response_model=List[FindingResponse], summary="Review Findings Alias")
def list_findings(
    cse_id: Optional[str] = Query(None, description="Filter by CSE code or ID"),
    priority: Optional[str] = Query(None, description="Filter by priority (CRITICAL, HIGH, MEDIUM, LOW)"),
    status_filter: Optional[str] = Query(None, alias="status", description="Filter by lifecycle status"),
    engine: Optional[str] = Query(None, description="Filter by detection engine"),
    control: Optional[str] = Query(None, description="Filter by control code"),
    date_from: Optional[datetime] = Query(None, description="Created after date"),
    date_to: Optional[datetime] = Query(None, description="Created before date"),
    search: Optional[str] = Query(None, description="Search keyword in title or why_flagged"),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Retrieve filtered and paginated list of candidate, under-review, and qualified findings."""
    return FindingService.list_findings(
        db=db,
        cse_id=cse_id,
        priority=priority,
        status_filter=status_filter,
        engine=engine,
        control=control,
        date_from=date_from,
        date_to=date_to,
        search=search,
        page=page,
        page_size=page_size,
    )


# 3. Review Queue Endpoint (TASK GROUP 4)
@router.get("/review/queue", response_model=ReviewQueueResponse, summary="Retrieve Examiner Review Queue")
def get_review_queue(
    cse_id: Optional[str] = Query(None, description="Filter by CSE"),
    priority: Optional[str] = Query(None, description="Filter by priority"),
    status_filter: Optional[str] = Query(None, alias="status", description="Filter by status"),
    search: Optional[str] = Query(None, description="Search keyword"),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Retrieve centralized supervisory review queue with aggregate counts and priority breakdown."""
    return FindingService.get_review_queue(
        db=db,
        cse_id=cse_id,
        priority=priority,
        status_filter=status_filter,
        search=search,
        page=page,
        page_size=page_size,
    )


# 4. Examiner Workspace Context (TASK GROUP 5)
@router.get("/findings/{finding_id}/workspace", response_model=ExaminerWorkspaceResponse, summary="Examiner Finding Workspace")
def get_finding_workspace(
    finding_id: str,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Retrieve complete 3-panel examiner workspace context:
    finding, why_flagged, expected_vs_observed, supporting_evidence, provenance,
    decision_history, available_actions, and remediation state.
    """
    workspace = FindingService.get_finding_workspace(db=db, finding_id=finding_id)
    check_cse_access(workspace.finding.cse_id, current_user, db)
    return workspace


# 5. Finding Detail
@router.get("/findings/{finding_id}", response_model=FindingResponse, summary="Retrieve Finding Detail")
@router.get("/review/findings/{finding_id}", response_model=FindingResponse, summary="Review Finding Detail Alias")
def get_finding_detail(
    finding_id: str,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Retrieve details of a single finding."""
    workspace = FindingService.get_finding_workspace(db=db, finding_id=finding_id)
    check_cse_access(workspace.finding.cse_id, current_user, db)
    return workspace.finding


# 6. Human Adjudication Actions (TASK GROUP 4 & 6)
@router.post("/findings/{finding_id}/validate", response_model=FindingResponse, summary="Validate Finding")
def validate_finding(
    finding_id: str,
    payload: Optional[FindingDecisionRequest] = None,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Human examiner action: Validates candidate finding after telemetry inspection."""
    return FindingService.apply_human_decision(
        db=db,
        finding_id=finding_id,
        target_status="VALIDATED",
        user=current_user,
        notes=payload.notes if payload else None,
        reason=payload.reason if payload else "Evidence inspection confirms discrepancy",
        action_name="VALIDATE",
    )


@router.post("/findings/{finding_id}/qualify", response_model=FindingResponse, summary="Qualify Finding")
def qualify_finding(
    finding_id: str,
    payload: Optional[FindingDecisionRequest] = None,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Human examiner action: Formally qualifies finding for regulatory remediation mandate."""
    return FindingService.apply_human_decision(
        db=db,
        finding_id=finding_id,
        target_status="QUALIFIED",
        user=current_user,
        notes=payload.notes if payload else None,
        reason=payload.reason if payload else "Statutory qualification under Section 70B",
        action_name="QUALIFY",
    )


@router.post("/findings/{finding_id}/reject", response_model=FindingResponse, summary="Reject Finding")
def reject_finding(
    finding_id: str,
    payload: Optional[FindingDecisionRequest] = None,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Human examiner action: Rejects candidate finding as false positive or documented maintenance."""
    return FindingService.apply_human_decision(
        db=db,
        finding_id=finding_id,
        target_status="REJECTED",
        user=current_user,
        notes=payload.notes if payload else None,
        reason=payload.reason if payload else "False positive or approved maintenance window",
        action_name="REJECT",
    )


@router.post("/findings/{finding_id}/override", response_model=FindingResponse, summary="Override Finding Weight")
def override_finding(
    finding_id: str,
    payload: Optional[FindingDecisionRequest] = None,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Human examiner action: Overrides model confidence or weight."""
    return FindingService.apply_human_decision(
        db=db,
        finding_id=finding_id,
        target_status="OVERRIDDEN",
        user=current_user,
        notes=payload.notes if payload else None,
        reason=payload.reason if payload else "Examiner discretionary override",
        action_name="OVERRIDE",
    )


@router.post("/findings/{finding_id}/evidence-demand", response_model=FindingResponse, summary="Issue Statutory Evidence Demand")
def issue_evidence_demand(
    finding_id: str,
    payload: EvidenceDemandRequest,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Human examiner action: Issues formal statutory evidence demand; sets finding to UNDER_REVIEW."""
    return FindingService.apply_human_decision(
        db=db,
        finding_id=finding_id,
        target_status="UNDER_REVIEW",
        user=current_user,
        notes=payload.notes,
        reason=payload.reason or "Statutory Order under Section 70B",
        action_name="EVIDENCE_DEMAND",
    )


# 7. Frontend Compatibility Adjudication Route
@router.post("/review/findings/{finding_id}/adjudicate", response_model=FindingResponse, summary="Adjudicate Finding Alias")
def adjudicate_finding_alias(
    finding_id: str,
    payload: FindingDecisionRequest,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Generic adjudication endpoint used by existing frontend client."""
    target_status = payload.status or "VALIDATED"
    return FindingService.apply_human_decision(
        db=db,
        finding_id=finding_id,
        target_status=target_status,
        user=current_user,
        notes=payload.notes,
        reason=payload.reason,
        action_name=f"ADJUDICATE_{target_status}",
    )


# 8. CSE Findings Alias
@router.get("/supervision/cses/{cse_id}/findings", response_model=List[FindingResponse], summary="List Findings for CSE")
def list_cse_findings(
    cse_id: str,
    current_user: User = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Retrieve findings for a specific Critical Sector Entity."""
    check_cse_access(cse_id, current_user, db)
    return FindingService.list_findings(db=db, cse_id=cse_id)
