"""Initial supervisory models

Revision ID: 3280af00b59c
Revises: 
Create Date: 2026-09-27 18:34:42.324827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid
from app.db.guid import GUID


# revision identifiers, used by Alembic.
revision: str = '3280af00b59c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applicability', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_capability', sa.Text(), nullable=True),
    sa.Column('expected_evidence', sa.Text(), nullable=True),
    sa.Column('assessment_criteria', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_code'), 'controls', ['code'], unique=True)
    op.create_index(op.f('ix_controls_domain'), 'controls', ['domain'], unique=False)
    op.create_index(op.f('ix_controls_public_id'), 'controls', ['public_id'], unique=True)
    op.create_index(op.f('ix_controls_severity'), 'controls', ['severity'], unique=False)
    op.create_index(op.f('ix_controls_status'), 'controls', ['status'], unique=False)
    op.create_table('cses',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('organization_type', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('soc_type', sa.String(length=64), nullable=False),
    sa.Column('claimed_capability', sa.Integer(), nullable=False),
    sa.Column('observed_capability', sa.Integer(), nullable=False),
    sa.Column('evidence_readiness', sa.Float(), nullable=False),
    sa.Column('readiness_category', sa.String(length=20), nullable=False),
    sa.Column('supervisory_priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('primary_signal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cses_name'), 'cses', ['name'], unique=False)
    op.create_index(op.f('ix_cses_public_id'), 'cses', ['public_id'], unique=True)
    op.create_index(op.f('ix_cses_sector'), 'cses', ['sector'], unique=False)
    op.create_index(op.f('ix_cses_status'), 'cses', ['status'], unique=False)
    op.create_index(op.f('ix_cses_supervisory_priority'), 'cses', ['supervisory_priority'], unique=False)
    op.create_index(op.f('ix_cses_tier'), 'cses', ['tier'], unique=False)
    op.create_table('permissions',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('assessment_cycles',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_readiness', sa.Float(), nullable=False),
    sa.Column('controls_assessed', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_cycles_cse_id'), 'assessment_cycles', ['cse_id'], unique=False)
    op.create_index(op.f('ix_assessment_cycles_period'), 'assessment_cycles', ['period'], unique=False)
    op.create_index(op.f('ix_assessment_cycles_public_id'), 'assessment_cycles', ['public_id'], unique=True)
    op.create_index(op.f('ix_assessment_cycles_status'), 'assessment_cycles', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('permission_id', app.db.guid.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('badge', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=False),
    sa.Column('role_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mfa_type', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('control_applicability',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('control_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('assessment_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('applicability_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'cse_id', 'assessment_id', name='uq_control_cse_assessment')
    )
    op.create_index(op.f('ix_control_applicability_assessment_id'), 'control_applicability', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_control_applicability_control_id'), 'control_applicability', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_applicability_cse_id'), 'control_applicability', ['cse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_applicability_cse_id'), table_name='control_applicability')
    op.drop_index(op.f('ix_control_applicability_control_id'), table_name='control_applicability')
    op.drop_index(op.f('ix_control_applicability_assessment_id'), table_name='control_applicability')
    op.drop_table('control_applicability')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_assessment_cycles_status'), table_name='assessment_cycles')
    op.drop_index(op.f('ix_assessment_cycles_public_id'), table_name='assessment_cycles')
    op.drop_index(op.f('ix_assessment_cycles_period'), table_name='assessment_cycles')
    op.drop_index(op.f('ix_assessment_cycles_cse_id'), table_name='assessment_cycles')
    op.drop_table('assessment_cycles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_cses_tier'), table_name='cses')
    op.drop_index(op.f('ix_cses_supervisory_priority'), table_name='cses')
    op.drop_index(op.f('ix_cses_status'), table_name='cses')
    op.drop_index(op.f('ix_cses_sector'), table_name='cses')
    op.drop_index(op.f('ix_cses_public_id'), table_name='cses')
    op.drop_index(op.f('ix_cses_name'), table_name='cses')
    op.drop_table('cses')
    op.drop_index(op.f('ix_controls_status'), table_name='controls')
    op.drop_index(op.f('ix_controls_severity'), table_name='controls')
    op.drop_index(op.f('ix_controls_public_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_domain'), table_name='controls')
    op.drop_index(op.f('ix_controls_code'), table_name='controls')
    op.drop_table('controls')
    # ### end Alembic commands ###
