"""add governance models and audit columns

Revision ID: 443b82663874
Revises: eec63c7cb808
Create Date: 2026-09-27 19:56:03.309092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid
from app.db.guid import GUID


# revision identifiers, used by Alembic.
revision: str = '443b82663874'
down_revision: Union[str, None] = 'eec63c7cb808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('weights_hash', sa.String(length=64), nullable=True),
    sa.Column('hyperparameters', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_model_id'), ['model_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_name', sa.String(length=128), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cse_count', sa.Integer(), nullable=False),
    sa.Column('signals_generated', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_run_id'), ['run_id'], unique=True)

    op.create_table('rule_versions',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('engine_slug', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logic_hash', sa.String(length=64), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_engine_slug'), ['engine_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_id'), ['rule_id'], unique=False)

    op.create_table('system_versions',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('release_name', sa.String(length=128), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_versions_version'), ['version'], unique=True)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.String(length=64), nullable=False, server_default='FINDING'))
        batch_op.add_column(sa.Column('entity_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('before', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('after', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('examiner_badge',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_version', sa.String(length=32), nullable=False, server_default='R-2.4'))
        batch_op.add_column(sa.Column('model_version', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('pipeline_version', sa.String(length=32), nullable=False, server_default='v3.1.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('pipeline_version')
        batch_op.drop_column('model_version')
        batch_op.drop_column('rule_version')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.alter_column('examiner_badge',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('request_id')
        batch_op.drop_column('after')
        batch_op.drop_column('before')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('actor_id')

    with op.batch_alter_table('system_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_versions_version'))

    op.drop_table('system_versions')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_versions_engine_slug'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_run_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_model_id'))

    op.drop_table('model_versions')
    # ### end Alembic commands ###
