"""Add evidence models

Revision ID: 54e9b70bd859
Revises: d07a823662cc
Create Date: 2026-09-27 18:59:14.852969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid
from app.db.guid import GUID


# revision identifiers, used by Alembic.
revision: str = '54e9b70bd859'
down_revision: Union[str, None] = 'd07a823662cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('control_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_event_id', sa.String(length=128), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_cse_id'), ['cse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_evidence_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source_system'), ['source_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_validation_status'), ['validation_status'], unique=False)

    op.create_table('evidence_control_links',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('evidence_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('control_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('mapping_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'control_id', name='uq_evidence_control_link')
    )
    with op.batch_alter_table('evidence_control_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_control_links_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_control_links_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('evidence_provenance',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('evidence_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('collector', sa.String(length=128), nullable=False),
    sa.Column('transmission_token', sa.String(length=128), nullable=True),
    sa.Column('source_host', sa.String(length=128), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('custody_chain', sa.Text(), nullable=True),
    sa.Column('received_by', sa.String(length=128), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_provenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_provenance_evidence_id'), ['evidence_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_provenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_provenance_evidence_id'))

    op.drop_table('evidence_provenance')
    with op.batch_alter_table('evidence_control_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_control_links_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_control_links_control_id'))

    op.drop_table('evidence_control_links')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_validation_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_state'))
        batch_op.drop_index(batch_op.f('ix_evidence_source_system'))
        batch_op.drop_index(batch_op.f('ix_evidence_sha256'))
        batch_op.drop_index(batch_op.f('ix_evidence_public_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_cse_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_control_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_category'))

    op.drop_table('evidence')
    # ### end Alembic commands ###
