"""add analytical signals and jobs models

Revision ID: 799b5f6bcf5f
Revises: 54e9b70bd859
Create Date: 2026-09-27 19:14:59.870755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid
from app.db.guid import GUID


# revision identifiers, used by Alembic.
revision: str = '799b5f6bcf5f'
down_revision: Union[str, None] = '54e9b70bd859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('engine_slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_engine_slug'), ['engine_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_status'), ['status'], unique=False)

    op.create_table('analytical_signals',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('engine_type', sa.String(length=64), nullable=False),
    sa.Column('engine_slug', sa.String(length=64), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('control_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('assessment_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('observed', sa.Text(), nullable=False),
    sa.Column('difference', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=True),
    sa.Column('recommended_for_sampling', sa.Boolean(), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.Column('control_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytical_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytical_signals_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytical_signals_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytical_signals_cse_id'), ['cse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytical_signals_engine_slug'), ['engine_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytical_signals_engine_type'), ['engine_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytical_signals_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytical_signals_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytical_signals_signal_id'), ['signal_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analytical_signals_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytical_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytical_signals_status'))
        batch_op.drop_index(batch_op.f('ix_analytical_signals_signal_id'))
        batch_op.drop_index(batch_op.f('ix_analytical_signals_priority'))
        batch_op.drop_index(batch_op.f('ix_analytical_signals_finding_id'))
        batch_op.drop_index(batch_op.f('ix_analytical_signals_engine_type'))
        batch_op.drop_index(batch_op.f('ix_analytical_signals_engine_slug'))
        batch_op.drop_index(batch_op.f('ix_analytical_signals_cse_id'))
        batch_op.drop_index(batch_op.f('ix_analytical_signals_control_id'))
        batch_op.drop_index(batch_op.f('ix_analytical_signals_assessment_id'))

    op.drop_table('analytical_signals')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_engine_slug'))

    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
