"""add signals, fusion, findings, and audit models

Revision ID: bea42f412cef
Revises: 799b5f6bcf5f
Create Date: 2026-09-27 19:24:56.436150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid
from app.db.guid import GUID


# revision identifiers, used by Alembic.
revision: str = 'bea42f412cef'
down_revision: Union[str, None] = '799b5f6bcf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fused_assessment_contexts',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('fusion_id', sa.String(length=64), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('control_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('signal_ids', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('historical_context', sa.Text(), nullable=True),
    sa.Column('peer_context', sa.Text(), nullable=True),
    sa.Column('process_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fused_assessment_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fused_assessment_contexts_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fused_assessment_contexts_cse_id'), ['cse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fused_assessment_contexts_fusion_id'), ['fusion_id'], unique=True)

    op.create_table('signals',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('control_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('observed', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_cse_id'), ['cse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_engine'), ['engine'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_id'), ['signal_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_signals_status'), ['status'], unique=False)

    op.create_table('signal_evidence_links',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('signal_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('evidence_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'evidence_id', name='uq_signal_evidence_link')
    )
    with op.batch_alter_table('signal_evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_evidence_links_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_evidence_links_signal_id'), ['signal_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('control_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('assessment_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('why_flagged', sa.Text(), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('evidence_strength', sa.String(length=16), nullable=False),
    sa.Column('completeness', sa.Integer(), nullable=False),
    sa.Column('uncertainty', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expected_state', sa.Text(), nullable=False),
    sa.Column('observed_state', sa.Text(), nullable=False),
    sa.Column('gap_summary', sa.Text(), nullable=False),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('control_version', sa.String(length=32), nullable=False),
    sa.Column('analytics_engine_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_cse_id'), ['cse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_findings_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('user_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('examiner_badge', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_events_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('finding_evidence_links',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('finding_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('evidence_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('relevance', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'evidence_id', name='uq_finding_evidence_link')
    )
    with op.batch_alter_table('finding_evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_evidence_links_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_evidence_links_finding_id'), ['finding_id'], unique=False)

    op.create_table('finding_signal_links',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('finding_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('signal_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'signal_id', name='uq_finding_signal_link')
    )
    with op.batch_alter_table('finding_signal_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_signal_links_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_signal_links_signal_id'), ['signal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_signal_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_signal_links_signal_id'))
        batch_op.drop_index(batch_op.f('ix_finding_signal_links_finding_id'))

    op.drop_table('finding_signal_links')
    with op.batch_alter_table('finding_evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_evidence_links_finding_id'))
        batch_op.drop_index(batch_op.f('ix_finding_evidence_links_evidence_id'))

    op.drop_table('finding_evidence_links')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_finding_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_signal_type'))
        batch_op.drop_index(batch_op.f('ix_findings_public_id'))
        batch_op.drop_index(batch_op.f('ix_findings_priority'))
        batch_op.drop_index(batch_op.f('ix_findings_cse_id'))
        batch_op.drop_index(batch_op.f('ix_findings_control_id'))
        batch_op.drop_index(batch_op.f('ix_findings_assessment_id'))

    op.drop_table('findings')
    with op.batch_alter_table('signal_evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_evidence_links_signal_id'))
        batch_op.drop_index(batch_op.f('ix_signal_evidence_links_evidence_id'))

    op.drop_table('signal_evidence_links')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_status'))
        batch_op.drop_index(batch_op.f('ix_signals_signal_id'))
        batch_op.drop_index(batch_op.f('ix_signals_priority'))
        batch_op.drop_index(batch_op.f('ix_signals_engine'))
        batch_op.drop_index(batch_op.f('ix_signals_cse_id'))
        batch_op.drop_index(batch_op.f('ix_signals_control_id'))

    op.drop_table('signals')
    with op.batch_alter_table('fused_assessment_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fused_assessment_contexts_fusion_id'))
        batch_op.drop_index(batch_op.f('ix_fused_assessment_contexts_cse_id'))
        batch_op.drop_index(batch_op.f('ix_fused_assessment_contexts_control_id'))

    op.drop_table('fused_assessment_contexts')
    # ### end Alembic commands ###
