"""Add user_cse_access and assessment dates

Revision ID: d07a823662cc
Revises: 3280af00b59c
Create Date: 2026-09-27 18:43:12.478963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid
from app.db.guid import GUID


# revision identifiers, used by Alembic.
revision: str = 'd07a823662cc'
down_revision: Union[str, None] = '3280af00b59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_cycles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_assessment_cycles_assigned_examiner', 'users', ['assigned_examiner_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('expected_outcomes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_controls_active'), ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controls_active'))
        batch_op.drop_column('expected_outcomes')
        batch_op.drop_column('active')

    with op.batch_alter_table('assessment_cycles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assessment_cycles_assigned_examiner', type_='foreignkey')

    # ### end Alembic commands ###
