"""add sampling, remediation, and verification models

Revision ID: eec63c7cb808
Revises: bea42f412cef
Create Date: 2026-09-27 19:36:50.067790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid
from app.db.guid import GUID


# revision identifiers, used by Alembic.
revision: str = 'eec63c7cb808'
down_revision: Union[str, None] = 'bea42f412cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sampling_runs',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sampling_parameters', sa.Text(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=128), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sampling_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sampling_runs_run_id'), ['run_id'], unique=True)

    op.create_table('remediations',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('remediation_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('finding_public_id', sa.String(length=64), nullable=False),
    sa.Column('cse_public_id', sa.String(length=64), nullable=False),
    sa.Column('cse_name', sa.String(length=255), nullable=False),
    sa.Column('control_ref', sa.String(length=64), nullable=False),
    sa.Column('mandate_title', sa.String(length=255), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.String(length=64), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=False),
    sa.Column('evidence_progress', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('artifacts', sa.Text(), nullable=False),
    sa.Column('milestones', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediations_cse_id'), ['cse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_cse_public_id'), ['cse_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_finding_public_id'), ['finding_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_remediation_id'), ['remediation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_remediations_status'), ['status'], unique=False)

    op.create_table('sampling_items',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('control_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('finding_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('cse_public_id', sa.String(length=64), nullable=False),
    sa.Column('cse_name', sa.String(length=255), nullable=False),
    sa.Column('control_ref', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('methodology', sa.String(length=32), nullable=False),
    sa.Column('sampling_reason', sa.Text(), nullable=False),
    sa.Column('evidence_strength', sa.String(length=16), nullable=False),
    sa.Column('evidence_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('assessment_period', sa.String(length=32), nullable=False),
    sa.Column('signals', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['sampling_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sampling_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sampling_items_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_items_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_items_cse_id'), ['cse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_items_cse_public_id'), ['cse_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_items_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_items_item_id'), ['item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sampling_items_methodology'), ['methodology'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_items_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_items_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sampling_items_status'), ['status'], unique=False)

    op.create_table('remediation_findings',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('remediation_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('finding_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediation_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_findings_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_findings_remediation_id'), ['remediation_id'], unique=False)

    op.create_table('verification_results',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('verification_id', sa.String(length=64), nullable=False),
    sa.Column('remediation_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('finding_id', app.db.guid.GUID(length=36), nullable=True),
    sa.Column('cse_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('mandate_public_id', sa.String(length=64), nullable=False),
    sa.Column('finding_public_id', sa.String(length=64), nullable=False),
    sa.Column('cse_public_id', sa.String(length=64), nullable=False),
    sa.Column('cse_name', sa.String(length=255), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('cycle', sa.String(length=32), nullable=False),
    sa.Column('lead_examiner', sa.String(length=128), nullable=False),
    sa.Column('statutory_standard', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at', sa.String(length=64), nullable=True),
    sa.Column('verification_verdict', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('evidence_completeness', sa.Integer(), nullable=False),
    sa.Column('merkle_root_hash', sa.String(length=128), nullable=False),
    sa.Column('remedial_summary', sa.Text(), nullable=False),
    sa.Column('supervisory_rationale', sa.Text(), nullable=False),
    sa.Column('submitted_artifacts', sa.Text(), nullable=False),
    sa.Column('pass_fail', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_results_cse_id'), ['cse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_cse_public_id'), ['cse_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_finding_public_id'), ['finding_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_mandate_public_id'), ['mandate_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_remediation_id'), ['remediation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_verification_id'), ['verification_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_verification_results_verification_verdict'), ['verification_verdict'], unique=False)

    op.create_table('verification_gates',
    sa.Column('id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('gate_id', sa.String(length=64), nullable=False),
    sa.Column('verification_result_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('remediation_id', app.db.guid.GUID(length=36), nullable=False),
    sa.Column('gate_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('evidence_requirement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_result_id'], ['verification_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_gates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_gates_gate_id'), ['gate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_gates_remediation_id'), ['remediation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_gates_verification_result_id'), ['verification_result_id'], unique=False)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remediation_id', app.db.guid.GUID(length=36), nullable=True))
        batch_op.add_column(sa.Column('target_type', sa.String(length=32), nullable=False, server_default='FINDING'))
        batch_op.add_column(sa.Column('target_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_events_remediation_id'), ['remediation_id'], unique=False)
        batch_op.create_foreign_key('fk_audit_events_remediation_id', 'remediations', ['remediation_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_events_remediation_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_events_remediation_id'))
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')
        batch_op.drop_column('remediation_id')

    with op.batch_alter_table('verification_gates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_gates_verification_result_id'))
        batch_op.drop_index(batch_op.f('ix_verification_gates_remediation_id'))
        batch_op.drop_index(batch_op.f('ix_verification_gates_gate_id'))

    op.drop_table('verification_gates')
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_verification_verdict'))
        batch_op.drop_index(batch_op.f('ix_verification_results_verification_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_remediation_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_mandate_public_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_finding_public_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_finding_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_cse_public_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_cse_id'))

    op.drop_table('verification_results')
    with op.batch_alter_table('remediation_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_findings_remediation_id'))
        batch_op.drop_index(batch_op.f('ix_remediation_findings_finding_id'))

    op.drop_table('remediation_findings')
    with op.batch_alter_table('sampling_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sampling_items_status'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_run_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_priority'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_methodology'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_finding_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_cse_public_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_cse_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_control_id'))
        batch_op.drop_index(batch_op.f('ix_sampling_items_case_id'))

    op.drop_table('sampling_items')
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediations_status'))
        batch_op.drop_index(batch_op.f('ix_remediations_remediation_id'))
        batch_op.drop_index(batch_op.f('ix_remediations_priority'))
        batch_op.drop_index(batch_op.f('ix_remediations_finding_public_id'))
        batch_op.drop_index(batch_op.f('ix_remediations_finding_id'))
        batch_op.drop_index(batch_op.f('ix_remediations_cse_public_id'))
        batch_op.drop_index(batch_op.f('ix_remediations_cse_id'))

    op.drop_table('remediations')
    with op.batch_alter_table('sampling_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sampling_runs_run_id'))

    op.drop_table('sampling_runs')
    # ### end Alembic commands ###
